import type { Job, Candidate } from "../types";

export const mockJobs: Job[] = [
  {
    id: "1",
    title: "Frontend Developer",
    company: "TechCorp",
    location: "Moscow",
    grade: "middle",
    salary: {
      min: 120000,
      max: 180000,
      currency: "RUB",
    },
    description:
      "We are looking for a skilled Frontend Developer to join our team...",
    requirements: [
      "React/Vue/Angular experience",
      "TypeScript knowledge",
      "2+ years of experience",
      "English B2+",
    ],
    benefits: [
      "Remote work",
      "Health insurance",
      "Learning budget",
      "Flexible schedule",
    ],
    status: "active",
    createdAt: "2024-01-15T10:00:00Z",
    updatedAt: "2024-01-15T10:00:00Z",
  },
  {
    id: "2",
    title: "Backend Developer",
    company: "DataSoft",
    location: "Saint Petersburg",
    grade: "senior",
    salary: {
      min: 200000,
      max: 300000,
      currency: "RUB",
    },
    description:
      "Senior Backend Developer position with focus on microservices...",
    requirements: [
      "Node.js/Python/Java experience",
      "Microservices architecture",
      "5+ years of experience",
      "Database design skills",
    ],
    benefits: [
      "Competitive salary",
      "Stock options",
      "Conference budget",
      "Team building events",
    ],
    status: "active",
    createdAt: "2024-01-10T14:30:00Z",
    updatedAt: "2024-01-10T14:30:00Z",
  },
  {
    id: "3",
    title: "DevOps Engineer",
    company: "CloudTech",
    location: "Remote",
    grade: "middle",
    salary: {
      min: 150000,
      max: 220000,
      currency: "RUB",
    },
    description: "DevOps Engineer to manage our cloud infrastructure...",
    requirements: [
      "AWS/Azure/GCP experience",
      "Docker and Kubernetes",
      "3+ years of experience",
      "CI/CD pipelines",
    ],
    benefits: [
      "Fully remote",
      "Equipment budget",
      "Certification support",
      "Flexible hours",
    ],
    status: "active",
    createdAt: "2024-01-20T09:15:00Z",
    updatedAt: "2024-01-20T09:15:00Z",
  },
  {
    id: "4",
    title: "UI/UX Designer",
    company: "DesignStudio",
    location: "Moscow",
    grade: "junior",
    salary: {
      min: 80000,
      max: 120000,
      currency: "RUB",
    },
    description:
      "Junior UI/UX Designer to work on mobile and web applications...",
    requirements: [
      "Figma/Sketch experience",
      "Portfolio required",
      "1+ years of experience",
      "Understanding of design principles",
    ],
    benefits: [
      "Mentorship program",
      "Design tools license",
      "Creative freedom",
      "Team collaboration",
    ],
    status: "active",
    createdAt: "2024-01-25T11:45:00Z",
    updatedAt: "2024-01-25T11:45:00Z",
  },
  {
    id: "5",
    title: "Full Stack Developer",
    company: "StartupInc",
    location: "Moscow",
    grade: "lead",
    salary: {
      min: 250000,
      max: 400000,
      currency: "RUB",
    },
    description: "Lead Full Stack Developer to build our MVP from scratch...",
    requirements: [
      "Full stack experience",
      "Team leadership skills",
      "7+ years of experience",
      "Startup experience preferred",
    ],
    benefits: [
      "Equity participation",
      "Fast career growth",
      "Latest technologies",
      "Impact on product",
    ],
    status: "active",
    createdAt: "2024-01-05T16:20:00Z",
    updatedAt: "2024-01-05T16:20:00Z",
  },
];

export const mockCandidates: Candidate[] = [
  {
    id: "1",
    firstName: "Алексей",
    lastName: "Петров",
    email: "alexey.petrov@email.com",
    phone: "+7 (999) 123-45-67",
    position: "Frontend Developer",
    experience: 3,
    skills: ["React", "TypeScript", "Svelte", "CSS", "HTML"],
    stage: "interview",
    rating: 4.5,
    notes: "Очень сильный кандидат, хорошие технические навыки",
    jobId: "1",
    createdAt: "2024-01-16T10:30:00Z",
    updatedAt: "2024-01-16T10:30:00Z",
  },
  {
    id: "2",
    firstName: "Мария",
    lastName: "Сидорова",
    email: "maria.sidorova@email.com",
    phone: "+7 (999) 234-56-78",
    position: "Backend Developer",
    experience: 5,
    skills: ["Node.js", "Python", "PostgreSQL", "Docker", "AWS"],
    stage: "technical",
    rating: 4.8,
    notes: "Отличные навыки работы с микросервисами",
    jobId: "2",
    createdAt: "2024-01-12T14:15:00Z",
    updatedAt: "2024-01-12T14:15:00Z",
  },
  {
    id: "3",
    firstName: "Дмитрий",
    lastName: "Козлов",
    email: "dmitry.kozlov@email.com",
    phone: "+7 (999) 345-67-89",
    position: "DevOps Engineer",
    experience: 4,
    skills: ["Kubernetes", "Docker", "AWS", "Terraform", "Jenkins"],
    stage: "screening",
    rating: 4.2,
    notes: "Хорошие знания облачных технологий",
    jobId: "3",
    createdAt: "2024-01-22T09:45:00Z",
    updatedAt: "2024-01-22T09:45:00Z",
  },
  {
    id: "4",
    firstName: "Анна",
    lastName: "Морозова",
    email: "anna.morozova@email.com",
    phone: "+7 (999) 456-78-90",
    position: "UI/UX Designer",
    experience: 2,
    skills: ["Figma", "Adobe Creative Suite", "Prototyping", "User Research"],
    stage: "applied",
    rating: 3.8,
    notes: "Молодой специалист с потенциалом",
    jobId: "4",
    createdAt: "2024-01-26T12:00:00Z",
    updatedAt: "2024-01-26T12:00:00Z",
  },
  {
    id: "5",
    firstName: "Сергей",
    lastName: "Волков",
    email: "sergey.volkov@email.com",
    phone: "+7 (999) 567-89-01",
    position: "Full Stack Developer",
    experience: 8,
    skills: ["React", "Node.js", "PostgreSQL", "Docker", "AWS", "Leadership"],
    stage: "final",
    rating: 4.9,
    notes: "Идеальный кандидат для лидерской позиции",
    jobId: "5",
    createdAt: "2024-01-08T15:30:00Z",
    updatedAt: "2024-01-08T15:30:00Z",
  },
  {
    id: "6",
    firstName: "Елена",
    lastName: "Новикова",
    email: "elena.novikova@email.com",
    phone: "+7 (999) 678-90-12",
    position: "Frontend Developer",
    experience: 1,
    skills: ["Vue.js", "JavaScript", "CSS", "HTML"],
    stage: "rejected",
    rating: 2.5,
    notes: "Недостаточно опыта для позиции",
    jobId: "1",
    createdAt: "2024-01-18T11:20:00Z",
    updatedAt: "2024-01-18T11:20:00Z",
  },
  {
    id: "7",
    firstName: "Игорь",
    lastName: "Соколов",
    email: "igor.sokolov@email.com",
    phone: "+7 (999) 789-01-23",
    position: "Backend Developer",
    experience: 6,
    skills: ["Java", "Spring Boot", "MongoDB", "Redis", "Kafka"],
    stage: "offered",
    rating: 4.6,
    notes: "Сильный кандидат, готов к офферу",
    jobId: "2",
    createdAt: "2024-01-14T13:45:00Z",
    updatedAt: "2024-01-14T13:45:00Z",
  },
  {
    id: "8",
    firstName: "Ольга",
    lastName: "Кузнецова",
    email: "olga.kuznetsova@email.com",
    phone: "+7 (999) 890-12-34",
    position: "UI/UX Designer",
    experience: 3,
    skills: ["Figma", "Sketch", "Principle", "User Testing", "Design Systems"],
    stage: "hired",
    rating: 4.7,
    notes: "Принята на работу",
    jobId: "4",
    createdAt: "2024-01-20T16:10:00Z",
    updatedAt: "2024-01-20T16:10:00Z",
  },
];

export const jobGrades: { value: string; label: string }[] = [
  { value: "junior", label: "Junior" },
  { value: "middle", label: "Middle" },
  { value: "senior", label: "Senior" },
  { value: "lead", label: "Lead" },
];

export const candidateStages: { value: string; label: string }[] = [
  { value: "applied", label: "Подал заявку" },
  { value: "screening", label: "Скрининг" },
  { value: "interview", label: "Собеседование" },
  { value: "technical", label: "Техническое" },
  { value: "final", label: "Финальное" },
  { value: "offered", label: "Предложение" },
  { value: "hired", label: "Принят" },
  { value: "rejected", label: "Отклонен" },
];
